### ISSUE TITLE
`testthat` files

### ISSUE THREAD

**Issue by rorynolan** [PerkinElmer/tiff#2]
Hi @PKI-Kent 
I'm trying to implement your tile-based TIFF reading in my `ijtiff` package.
Would you mind sharing with me the files you used in your `testthat` tests? I'd like to have your tests, they look good.
Thanks,
Rory

**Comment by AB-Kent** [comment]
I'll check, I can probably give them to you. They are fairly large (about 250 MB total) which is one reason I didn't check them in to the repo...

**Comment by rorynolan** [comment]
Hi @PKI-Kent, sorry to bother you again. 
Do you think you can send me those files? If not, do you know where I can get some tile-based TIFFs for testing this new part of the package?
Thanks,
Rory

**Comment by AB-Kent** [comment]
Unfortunately the specific files I used are not available for distribution. There are tiled TIFF files available for public use at http://downloads.openmicroscopy.org/images/Vectra-QPTIFF/perkinelmer/
