### ISSUE TITLE
missing tiff.h file on Mac

### ISSUE THREAD

**Issue by cdarabos** [PerkinElmer/tiff#3]
> devtools::install_github("PerkinElmer/tiff")
Downloading GitHub repo PerkinElmer/tiff@master
from URL https://api.github.com/repos/PerkinElmer/tiff/zipball/master
Installing tiff
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/px/y83xsm8n0gq129hk7_5gn09r0000gn/T/RtmpBa2voN/devtools78c5b0a00c6/PerkinElmer-tiff-3cb58e4'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5/Resources/library' --install-tests 

* installing *source* package ‘tiff’ ...
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/include   -fPIC  -Wall -g -O2  -c common.c -o common.o
In file included from common.c:1:
./common.h:5:10: fatal error: 'tiff.h' file not found
#include <tiff.h>
         ^~~~~~~~
1 error generated.
make: *** [common.o] Error 1
ERROR: compilation failed for package ‘tiff’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tiff’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/tiff’
Installation failed: Command failed (1)

**Comment by AB-Kent** [comment]
I suspect you will have to install libtiff on your Mac before installing the tiff package. A couple of options for libtiff:
https://stackoverflow.com/questions/24775252/r-how-to-install-package-tiff-on-mac-os-x-mavericks
https://mac-dev-env.patrickbougie.com/libtiff/
