### ISSUE TITLE
ijtiff

### ISSUE THREAD

**Issue by maelle** [PerkinElmer/tiff#4]
:wave: @AB-Kent! Are you aware of the `ijtiff` package https://github.com/ropensci/ijtiff by @rorynolan? Just for info!

**Comment by AB-Kent** [comment]
Yes, we collaborated to incorporate some of my `tiff` changes into `ijtiff` - https://github.com/ropensci/ijtiff/commit/b90a54. When I forked `tiff` I didn't realize that `ijtiff` is a general-purpose TIFF library; the docs were very focused on ImageJ TIFF files.
